// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_belengv.Models;

namespace Mission06_belengv.Migrations
{
    [DbContext(typeof(AddMovieContext))]
    [Migration("20230219075053_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_belengv.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            EntryId = 1,
                            CategoryId = 3,
                            Director = "Nikolas Sparks",
                            Edited = false,
                            LentTo = "Megan",
                            Notes = "Best movie ever!!",
                            Rating = "PG-13",
                            Title = "The Longest Ride",
                            Year = (ushort)2014
                        },
                        new
                        {
                            EntryId = 2,
                            CategoryId = 1,
                            Director = "Sam Raimi",
                            Edited = true,
                            LentTo = "Carla",
                            Notes = "Andrew Garfiels is everyhting!!",
                            Rating = "PG",
                            Title = "The Amazing Spider Man",
                            Year = (ushort)2012
                        },
                        new
                        {
                            EntryId = 3,
                            CategoryId = 1,
                            Director = "Tony Scott",
                            Edited = false,
                            LentTo = "Mom",
                            Notes = "How can this movie be so good? ",
                            Rating = "PG-13",
                            Title = "Top Gun",
                            Year = (ushort)2022
                        });
                });

            modelBuilder.Entity("Mission06_belengv.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Action/Adventure"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Family"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Horror/Suspense"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Miscellaneous"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Television"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "VHS"
                        });
                });

            modelBuilder.Entity("Mission06_belengv.Models.ApplicationResponse", b =>
                {
                    b.HasOne("Mission06_belengv.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
